/** The raid page's elements (games/raid/index.html), found once. */

export const $ = <T extends HTMLElement>(id: string): T => document.getElementById(id) as T;

export const ui = {
  bossTitle: $('boss-title'),
  battle: $('battle'),
  battlePicture: $<HTMLImageElement>('battle-picture'),
  battleBackdrop: $<HTMLImageElement>('battle-backdrop'),
  result: $('result'),
  resultTitle: $('result-title'),
  resultText: $('result-text'),
  resultSorts: [...document.querySelectorAll<HTMLButtonElement>('.rd-sort')],
  moreStats: $<HTMLButtonElement>('more-stats'),
  statsPop: $('stats-pop'),
  statsPick: $('stats-pick'),
  statsTitle: $('stats-title'),
  statsRows: $('stats-rows'),
  statsAxis: $('stats-axis'),
  statsClose: $<HTMLButtonElement>('stats-close'),
  resultRows: $('result-rows'),
  tags: $('boss-tags'),
  bossName: $('boss-name'),
  bossPct: $('boss-pct'),
  bossFill: $('boss-fill'),
  intentText: $('intent-text'),
  prep: $('prep'),
  prepBackdrop: $<HTMLImageElement>('prep-backdrop'),
  prepPicture: $<HTMLImageElement>('prep-picture'),
  prepBossName: $('prep-boss-name'),
  prepMoves: $('prep-moves'),
  prepPhases: $('prep-phases'),
  prepRewards: $('prep-rewards'),
  prepSlots: $('prep-slots'),
  prepStatus: $('prep-status'),
  start: $<HTMLButtonElement>('start'),
  join: $<HTMLButtonElement>('join'),
  leave: $<HTMLButtonElement>('leave'),
  begin: $<HTMLButtonElement>('begin'),
  round: $('round'),
  turnText: $('turn-text'),
  turnFill: $('turn-fill'),
  actions: [...document.querySelectorAll<HTMLButtonElement>('[data-action]')],
  actNote: $('act-note'),
  healPick: $('heal-pick'),
  healOptions: $('heal-options'),
  party: $('party'),
  logPanel: $<HTMLDetailsElement>('log-panel'),
  log: $('log'),
  toast: $('toast'),
  gearPop: $('gear-pop'),
  gearFit: $('gear-pop').querySelector('.rd-gear-fit') as HTMLElement,
  gearFrame: $<HTMLIFrameElement>('gear-frame'),
  gearClose: $<HTMLButtonElement>('gear-close'),
};
